project:
  type: book
  output-dir: docs

book:
  title: "GF0604 Procesamiento de datos geogr√°ficos 2023-I"
  author: "Manuel Vargas"
  date: "2023-01-17"
  chapters:
    - index.qmd
    - part: parte-i-introduccion-programacion_computadoras.qmd
      chapters:
        - 01-pensamiento_computacional-arquitectura_computadoras-lenguajes_programacion.qmd
        - 02-interaccion_humano_computadora.qmd
        - 03-gdal.qmd
        - 04-reproducibilidad.qmd
        - 05-markdown.qmd
        - 06-git.qmd
    - part: parte-ii-r.qmd
      chapters:
        - 07-r.qmd
        - 08-quarto.qmd
        - 09-tidyverse.qmd
        - 10-dplyr.qmd
    - part: parte-iii-graficacion.qmd
      chapters:
        - 11-ggplot2-plotly.qmd     
    - part: parte-iv-geoespacial.qmd
      chapters:        
        - 12-introduccion-manejo-datos-geoespaciales.qmd
        - 13-operaciones-datos-atributos.qmd
        - 14-operaciones-datos-espaciales.qmd
    - part: parte-vi-evaluaciones.qmd
      chapters:
        - examen_corto-01.qmd
        - tarea-01.qmd
        - examen_corto-02.qmd
        - examen_corto-03.qmd
        - tarea-02.qmd

bibliography: referencias.bib

format:
  html:
    lang: es
    theme: cosmo
  pdf:
    documentclass: scrreprt



